### PR TITLE
Add reshaped array wrapper

### PR DESCRIPTION
**Pull request by dhairyagandhi96**
Useful for cases when reshaping is necessary.

Ref: FluxML/Flux.jl#536

### CODE REVIEW

**Comment by MikeInnes** [comment]
:+1: Thanks!

**Comment by maleadt** [comment]
This didn't get a test though. @dhairyagandhi96, care to add one? Thanks!

**Comment by dhairyagandhi96** [comment]
Sure, absolutely!
I'm on it

**Comment by maleadt** [comment]
Any update?

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/Adapt.jl/commit/4cfb6e9ae07e68270c0ddc9e4d677dbcba6e2bc2

**Comment by dhairyagandhi96** [comment]
Ah, I just saw the message. Thanks for that! I thought I had already sent that PR. My apologies.

**Comment by maleadt** [comment]
No problem, figured it would be easier to do it myself before losing track of the issue.

**Pull request merged**
